# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 18227066a348f058f90064ad3db669ed503c2842046b075d76bdd6a96a5440d0c2a1dbc32d29f127d186dfd30b606a47c6e270f376fa7e36a4568ebf3278bf6a

test:
  secret_key_base: a66856f31279829c463be3124271b5fe8d88e51857ba4cac59a3c4e745499088a9436f2678249abb4a7e85f6cbe9529e67d0de30a66ae38259d88a72ed8cdb7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
